### ISSUE TITLE
Subscription Switch not working

### ISSUE THREAD

**Issue by ae94** [Rebilly/rebilly-js-sdk#86]
Here's my code:
const api = RebillyAPI({ apiKey: nconf.get('REBILLY_API_KEY'), sandbox: nconf.get('NODE_ENV') == 'development' });
api.subscriptions.switch(...) calls https://api-sandbox.rebilly.com/v2.1/subscriptions/{id}/switch 
but it seems that this endpoint does not exist. Getting a different 404 as usual here:
{
  "title": "The origin server did not find a current representation for the target resource or is not willing to disclose that one exists",
  "status": 404,
  "error": "Not Found - The requested item doesn't exist.",
  "details": []
}

Can you check on this please?

**Comment by 2e3s** [comment]
Do you use the latest SDK? We've removed `switch` long ago. It's replaced by `changePlan` now.

**Comment by 2e3s** [comment]
This is a removed functionality. Try subscription's change-plan in https://github.com/Rebilly/rebilly-js-sdk/releases/tag/8.2.0
